### ISSUE TITLE
Not enough GPU memory

### ISSUE THREAD

**Issue by ZxUkr** [sxyu/svox2#99]
What is requirements for hardware? On RTX 3070 with 8Gb I have this error very often. Is exist some solve in this case?

**Comment by Learningm** [comment]
Probably 20GB around during training.

**Comment by sarafridov** [comment]
It depends on the scene; for scenes without a background you should be able to use <11GB on GPU during training. Some strategies you can use to reduce memory usage if you only have a lower-memory GPU:
- reduce batch size
- reduce resolution (if you go OOM during an upsampling step, you can try upsampling to not quite as high a final resolution)
- use SGD instead of RMSProp
